### PR TITLE
Update TC_TRUST uri

### PR DESCRIPTION
**Pull request by rony-vargas**
Added an additional LetsEncrypt Root CA certificate to make it compatible with TTNv3 and TTNv2 at same time

### CODE REVIEW

**Comment by mpous** [comment]
what do you think @jmarcelino?

**Comment by jmarcelino** [comment]
Nice, thank you very much @rony-vargas you saved me doing this!
@mpous looks good to me you can go ahead I think

**Comment by mpous** [comment]
Thank you @rony-vargas !

**Comment by rony-vargas** [comment]
Anytime @jmarcelino & @mpous

**Pull request merged**
